Попытка создать реквест
Viktoreja/Course pull request #1
Opened 2021-07-08 19:09 UTC by Viktoreja

2021-07-09 05:32 UTC, stepan-l requested changes

2021-07-09 05:40 UTC, Viktoreja commented on Task1/app/src/main/java/com/example/task1/LoginFragment.kt
> +    fun ClickListener(view: View){
Переход не работает, я не могу понять как прицепить это к кнопке. Взять её id через findViewById не получается, пытался подключить через оnClick в xml файле, в таком случае при нажатии на кнопку приложение просто закрывается. Подскажите, пожалуйста, как это лучше сделать

2021-07-09 05:56 UTC, stepan-l requested changes

2021-07-09 05:56 UTC, stepan-l commented on Task1/app/src/main/java/com/example/task1/LoginFragment.kt
> +    fun ClickListener(view: View){
обычно инициализацию вьюшек лэйоута (установка кликлистенеров, запуск анимации и т.д) проводят в функции onViewCreated

т.е в этом классе переопределяем ф-ю onViewCreated() переопредели ее следующим образом
    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        view.findViewById<View>().setOnClickListener{
           ClickListener(it)
         }
    }

2021-07-12 10:56 UTC, stepan-l approved these changes

2021-07-12 13:35 UTC, merged